# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tbc_best_bivariate_split <- function(X, y, priorRatio, coefs) {
    .Call(`_TBC_tbc_best_bivariate_split`, X, y, priorRatio, coefs)
}

tbc_best_numeric_splits <- function(X, y, priorRatio, feature_order = NULL) {
    .Call(`_TBC_tbc_best_numeric_splits`, X, y, priorRatio, feature_order)
}

