// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// tbc_best_bivariate_split
Rcpp::List tbc_best_bivariate_split(Rcpp::NumericMatrix X, Rcpp::IntegerVector y, Rcpp::NumericVector priorRatio, Rcpp::NumericVector coefs);
RcppExport SEXP _TBC_tbc_best_bivariate_split(SEXP XSEXP, SEXP ySEXP, SEXP priorRatioSEXP, SEXP coefsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type priorRatio(priorRatioSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type coefs(coefsSEXP);
    rcpp_result_gen = Rcpp::wrap(tbc_best_bivariate_split(X, y, priorRatio, coefs));
    return rcpp_result_gen;
END_RCPP
}
// tbc_best_numeric_splits
Rcpp::List tbc_best_numeric_splits(const Rcpp::NumericMatrix& X, const Rcpp::IntegerVector& y, const Rcpp::NumericVector& priorRatio, Rcpp::Nullable<Rcpp::IntegerVector> feature_order);
RcppExport SEXP _TBC_tbc_best_numeric_splits(SEXP XSEXP, SEXP ySEXP, SEXP priorRatioSEXP, SEXP feature_orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type priorRatio(priorRatioSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::IntegerVector> >::type feature_order(feature_orderSEXP);
    rcpp_result_gen = Rcpp::wrap(tbc_best_numeric_splits(X, y, priorRatio, feature_order));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_TBC_tbc_best_bivariate_split", (DL_FUNC) &_TBC_tbc_best_bivariate_split, 4},
    {"_TBC_tbc_best_numeric_splits", (DL_FUNC) &_TBC_tbc_best_numeric_splits, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_TBC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
